name: Deploy Kedro Viz to GitHub Pages

on:
  push:
    branches:
      - "*" # Revert to main before merge
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt kedro-datasets
          pip uninstall -y kedro-telemetry
      - name: Build...
        run: kedro viz build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
